services:
  caddy:
    image: x1roko/caddy-l4:latest
    container_name: sni_proxy
    command: caddy run --config /etc/caddy/config.json
    volumes:
      - ./config.json:/etc/caddy/config.json:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - dns

  dns:
    image: powerdns/dnsdist-19:latest
    container_name: dnsdist
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853/tcp"
      - "8053:8053/tcp"
    volumes:
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
      - ./certs:/etc/dnsdist/certs:ro
    restart: unless-stopped
    networks:
      - dns

networks:
  dns:
    driver: bridge
